#
# FILE        :app.yaml
# DATE        :2017.12.20
# DESCRIPTION :アプリケーション設定
# NAME        :Hikaru Yoshida
#

# 言語
runtime: python27

# APIバージョン
api_version: 1

# マルチスレッド
threadsafe: true

# URLと挙動
handlers:

# staticの参照とアップロード
- url: /static/(.*\.(css|ico|js))$
  static_files: static/\1
  upload: static/(.*\.(css|ico|js))$

# その他はmain.appを実行
- url: /.*
  script: main.app

# 使用するライブラリとバージョン
libraries:

# jinja2テンプレートエンジン
- name: jinja2
  version: latest

# Google App Engine API
- name: webapp2
  version: latest
